In [1]:
import numpy as np

In [4]:
X = [[1 , 2 , 3 , 4],
    [2.0 , 2 , 1 , 5],
    [1.1 , 2.1 , 0 , 1.1]]

In [2]:
np.random.seed(0)

In [3]:
class Layer_Dence:
    def __init__(self , n_inputs , n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs , n_neurons)
        self.biases = np.zeros((1 , n_neurons))

    def forward(self , inputs ):
        self.outputs = np.dot(inputs , self.weights ) + self.biases
        

In [5]:
layer1 = Layer_Dence(4 , 5)
layer2 = Layer_Dence(5 , 4)

In [6]:
layer1.forward(X)
print(f"{layer1.outputs}")

[[0.15763246 1.26394709 0.21385037 0.36517514 0.06039617]
 [0.33859641 1.16251601 0.1390008  0.59623622 0.07296975]
 [0.02552158 0.40788456 0.05330876 0.25925974 0.19770653]]


In [7]:
layer2.forward(layer1.outputs)
print(f"{layer2.outputs}")

[[ 0.25443086 -0.20717053  0.00767932 -0.02338728]
 [ 0.15476944 -0.23584537  0.01317269 -0.03451718]
 [ 0.09554215 -0.07740247 -0.01177906 -0.00943635]]
